name: Flutter Build

on:
 push:
    branches:
      - main

jobs:
 build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.6'
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Build Linux
        run: flutter build linux
        working-directory: ./app
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ./app/build/linux/x64/release/bundle

 build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.6'
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Build Windows
        run: flutter build windows
        working-directory: ./app
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ./app/build/windows/runner/Release/

 build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.6'
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./app
      - name: Build macOS
        run: flutter build macos
        working-directory: ./app
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: ./app/build/macos/Build/Products/Release/
